---
# Name of the cluster to create
cluster_name: "hydra"
# Name of template to build master and worker nodes from.
ovirt_base_template_name: "kubernetes"
#### Networking related
# IP address of the desired controlplane endpoint
kubernetes_controlplane_endpoint: "10.0.7.10"
# DNS record of the controlplane endpoint
kubernetes_controlplane_dns_endpoint: "api.hydra.kube.oxide.one"

master_nodes:
  count: 3
  cores: 8
  ram: 10240
  disk: 35
  naming: kube-master
  network: kube
  starting_ip:  "10.0.7.11"

worker_nodes:
  count: 4
  cores: 6
  ram: 8192
  disk: 35
  naming: kube-node
  network: kube
  role: "worker"

special_nodes:
  count: 2
  cores: 8
  ram: 10240
  disk: 35
  naming: kube-special
  network: wireguard
  role: "torrent"
