---
# Name of the cluster to create
cluster_name: "hydra"
# Number of master nodes to create
master_nodes: 3
# Number of worker nodes to create
worker_nodes: 4
# Name of template to build master and worker nodes from.
ovirt_base_template_name: "kubernetes"
#### Networking related
# What network to create the cluster on
kubernetes_network: "kube"
# Any additional networks to add the cluster to
# Required var for ovirt.
ovirt_vm_networks:
  - "{{ kubernetes_network }}"
cluster_network: "{{ networks[kubernetes_network] }}"
fqdn_end: "{{ cluster_network.subdomain }}.{{ domain }}"
# Start ip for the master nodes. Master nodes are created with static ip addresses
master_nodes_starting_ip: "10.0.7.11"

### Master node specs
master_node_cores: 8
master_node_ram: 10240
master_node_disk_size: 35
master_node_naming: "kube-master"

### Worker node specs
worker_node_cores: 6
worker_node_ram: 8192
worker_node_disk_size: 35
worker_node_naming: "kube-node"
kubernetes_controlplane_endpoint: "10.0.7.10"
kubernetes_controlplane_dns_endpoint: "api.hydra.kube.oxide.one"
