---
ansible_user: 'vyos'
ansible_connection: network_cli
ansible_network_os: vyos
base_image_name: "vyos-1.2.4-amd64.qcow2"

cpus: 4
memory: 6144
disk_size: 7.5G

vm_net_opts: "--network=network:{{ system_networks | join(' --network=network:') | regex_replace('virtual','default') }}"

network_address: dhcp
network_addresses:
  out: dhcp

network_mapping:
  eth0: 'out'
  eth1: 'server'
  eth2: 'virtual'
  eth3: 'utility'
  eth4: 'zoned'
  eth5: 'kube'
  eth6: 'wireguard'
  eth7: 'management'
