---
- name: "Setup acme.sh"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Setup acme.sh"
  include_tasks: certs.yml
  when: state|default('present') == 'present'

- name: "Renew all acme.sh certificates"
  include_tasks: renew.yml
  when: state|default('present') == 'renew'

- name: "Remove acme.sh"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'

