---
- name: "Ensure that necessary packages are installed"
  dnf:
    name:
      - anacron
      - wget
    state: present
  become: yes

- name: "Make sure that {{ acme_default_user }} group is created"
  group:
    name: "{{ acme_default_user }}"
    system: yes
    state: present
  become: yes

- name: "Make sure that {{ acme_default_user }} user is created"
  become: yes
  user:
    name: "{{ acme_default_user }}"
    group: "{{ acme_default_user }}"
    home: "{{ acme_default_user_homedir }}"
    createhome: yes
    state: present
    shell: /sbin/nologin
    system: yes

- name: "Download acme.sh"
  get_url:
    url: https://get.acme.sh
    dest: /tmp/acme.sh
    mode: '0777'

- name: "Install acme.sh"
  command: "/tmp/acme.sh --install"
  become: yes
  become_user: "{{ acme_default_user }}"
  register: output

- name: "Allow Sudo access for acme to reload nginx"
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/100-acme-nginx
  become: yes
