---
- name: "Get Join token from api server"
  command: "kubeadm token create --print-join-command"
  become: yes
  register: join_command
  delegate_to: "kube-apiserver"

- name: "Set the join token variable"
  set_fact:
    join_token_command: "{{ join_command.stdout }}"

- name: "Add worker nodes"
  include_role:
    name: app/kubernetes/add_hosts
  vars:
    role: node
    hosts_to_add: "{{ kworker_diff }}"
    extra_group: "kube-node-added"

- name: "Add special nodes"
  include_role:
    name: app/kubernetes/add_hosts
  vars:
    role: special
    hosts_to_add: "{{ kspecial_diff }}"
    extra_group: "kube-node-added"
