---
- ovirt_network:
    data_center: "{{ ovirt_datacenter }}"
    name: "{{ item.key }}"
    vlan_tag: "{{ item.value.vlan_id }}"
    label: "{{ item.value.subdomain }}"
    state: absent
    auth: "{{ ovirt_auth }}"
  when: item.value.vlan_id is defined
  with_dict: "{{ networks }}"
