---
- name: "Modify oVirt template for use as a system"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Remove modified oVirt template"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'

