---
- set_fact: vm_network="{{ networks[ovirt_nic_network].gateway | ipv4('host/prefix') }}"
- name: "Create ovirt VM and modify template"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: present
    name: "base_image"
    cpu_cores: 8
    template: "{{ ovirt_base_template_name }}"
    cluster: "{{ ovirt_cluster_name }}"
    type: "server"
    operating_system: "other_linux"
    serial_console: "yes"
    nics:
      - interface: "virtio"
        name: "{{ ovirt_nic_network }}"
        profile_name: "{{ ovirt_nic_network }}"
  register: ovirt_created_vm

- name: "Start ovirt VM"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cloud_init:
      custom_script: |
        {% if ovirt_template_upgrade_all %}
        package_update: true
        package_upgrade: true
        {% endif %}
        packages:
        {% for package in ovirt_template_packages %}
         - {{ package }}
        {% endfor %}
        runcmd:
        {% if ovirt_template_selinux_disabled %}
         - sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
        {% endif %}
         - rm -rf /var/lib/cloud/*
        {% for unit in ovirt_template_enabled_services %}
         - systemctl enable {{ unit }}
        {% endfor %}
        power_state:
         delay: "0"
         mode: poweroff
         message: Bye Bye
         timeout: 30
         condition: True
    cloud_init_persist: True
    state: "running"
    name: "base_image"

