---
- name: "Setup NGINX as proxy server"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Remove NGINX and proxy server config"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'


