---

- set_fact: domain_name="{{ item.value.subdomain }}.{{ domain }}"
- set_fact: arpa="{{ item.value.gateway.split('.')[2::-1] | join('.') }}"
- name: "Set networks"
  vyos_command:
    commands:
      - configure
      - set service dhcp-server global-parameters "zone {{ domain_name }}. { primary {{ dns_server }}; key rndc-key; }"
      - set service dhcp-server global-parameters "zone {{ arpa }}.in-addr.arpa. { primary {{ dns_server }}; key rndc-key; }"
      - commit
      - save
  when: item.key != 'out'

