---
- name: "Template out Ethernet and High Availability config for VyOS"
  vyos_config:
    src: setup_solar.j2
    save: yes
  when: state|default('solar') == 'solar'

- name: "Template out Ethernet and config for Lunar"
  include_tasks: lunar.yml
  when: state|default('lunar') == 'lunar'

- name: "Template out eclipse config"
  vyos_config:
    src: setup_eclipse.j2
    save: yes
  when: state|default('eclipse') == 'eclipse'
- name: "Template out DHCPD config for VyOS"
  vyos_config:
    src: dhcpd.j2
    save: yes
  when: state|default('dhcpd') == 'dhcpd' and cluster_index == '1'
