- set_fact: net_name="{{ network.value }}" address="{{ network_addresses[ network.value ] }}"
- set_fact: domain_name="{{ system_networks[ network.value ].subdomain }}.{{ domain }}"
- set_fact: full_address="{{ address }}/24" dns_server="{{ dns_server }}"
- set_fact: subnet="{{ full_address | ipaddr('network') }}"
- set_fact: network_start="10.0.{{ system_networks[ network.value ].gateway.split('.')[2] }}.{{ dhcp_start }}"
- set_fact: network_end="10.0.{{ system_networks[ network.value ].gateway.split('.')[2] }}.{{ dhcp_end }}"
- set_fact: precmd="service dhcp-server shared-network-name {{ net_name }} subnet {{ subnet }}/24 "
- name: "Set DHCP Server up"
  vyos_command:
    commands:
      - configure
      - "delete {{ precmd }} dns-server"
      - "set {{ precmd }} dns-server {{ dns_server }}"
      - commit
      - save

