---
- debug:
    msg: |
      Please run the following commands on VyOS
      ---------------
      configure
      set interfaces wireguard wg1 address {{ vpn_network_address }}/24
      set interfaces wireguard wg1 description 'tunnel to {{ ansible_hostname }}'.vm.{{ domain }}
      set interfaces wireguard wg1 peer {{ ansible_hostname }} endpoint {{ ansible_hostname }}:55107
      set interfaces wireguard wg1 peer {{ ansible_hostname }} allowed-ips {{ vpn_network }}
      set interfaces wireguard wg1 peer {{ ansible_hostname }} pubkey '{{ wireguard_public_key }}'
      set interfaces wireguard wg1 peer {{ ansible_hostname }} persistent-keepalive 25
      set interfaces wireguard wg1 private-key (YOUR PRIVATE KEY)
      ---------------
      And store the output of the final command as a var at local_wireguard_pubkey
      Currently it appears to be {{ local_wireguard_pubkey }}
      =============================================================================
      Have you run the commands printed above? (yes/no)
  register: pause
  when: ( action == 'install_wireguard' or action == 'all' or action == 'setup_wireguard' )

