---
- name: Ensure NGINX conf dir is created
  file:
    path: /etc/nginx/conf
    owner: nginx
    group: web
    mode: 0755
    state: directory

- name: Copy relevant files across
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf/{{ item }}"
  with_items:
    - gzip.conf
    - proxy.conf
    - mime.types

- name: "Template out ssl.conf"
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf/ssl.conf
    owner: root
    group: root
    mode: 0750
- name: "Template temp"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0750

- name: "Start and enable nginx"
  systemd:
    name: nginx
    state: restarted
    enabled: yes
