---

- name: "Modprobe wireguard"
  modprobe:
    name: wireguard
    state: present

- name: "Generate Private key for wireguard"
  shell: wg genkey
  register: wireguard_private_key

- name: "Set the STDOUT as the private key"
  set_fact: wireguard_private_key="{{ wireguard_private_key.stdout }}"

- name: "Generate Public key for wireguard"
  shell: "echo {{ wireguard_private_key }} | wg pubkey"
  register: wireguard_public_key

- name: "Set the STDOUT as the public key"
  set_fact: wireguard_public_key="{{ wireguard_public_key.stdout }}"

- name: "Create wireguard dir"
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: wheel
    mode: '0750'

- name: "Template out the wireguard server config"
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: wheel
    mode: 0750

- name: "Enable and start wireguard"
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: yes
