---
- include_role:
    name: virt/ovirt/auth
  when: ovirt_auth is not defined

- name: "Stop the ovirt virtual machine"
  delegate_to: 127.0.0.1
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: stopped
    name: "{{ inventory_hostname }}"

- name: "Destroy the ovirt virtual machine"
  delegate_to: 127.0.0.1
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: absent
    name: "{{ inventory_hostname }}"
