---
- include_role:
    name: virt/ovirt/auth
  when: ovirt_auth is not defined

- name: "Create virtual machine on ovirt"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Start virtual machine on ovirt"
  include_tasks: start.yml
  when: state|default('present') == 'started'

- name: "Stop virtual machine on ovirt"
  include_tasks: setup.yml
  when: state|default('present') == 'stopped'

- name: "Remove virtual machine on ovirt"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'

