---
- name: "Create ovirt vm {{ inventory_hostname }}"
  delegate_to: "127.0.0.1"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: "present"
    name: "{{ inventory_hostname }}"
    template: "{{ ovirt_base_template_name }}"
    cluster: "{{ ovirt_cluster_name }}"
    memory: "{{ ovirt_vm_ram }}MiB"
    high_availability: "{{ ovirt_vm_ha }}"

- name: "Add nics to {{ inventory_hostname }}"
  delegate_to: "127.0.0.1"
  ovirt_nic:
    auth: "{{ ovirt_auth }}"
    vm: "{{ inventory_hostname }}"
    name: "{{ item }}"
    profile: "{{ item }}"
    network: "{{ item }}"
    interface: "virtio"
    state: "present"
  with_list: "{{ ovirt_vm_networks }}"
