---
- name: "Start ovirt VM"
  delegate_to: "127.0.0.1"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: "running"
    name: "{{ inventory_hostname }}"
    cloud_init:
      host_name: "{{ inventory_hostname }}"
      authorized_ssh_keys: "{{ ssh_keys[ovirt_vm_admin_user] }}"
      user_name: "{{ ovirt_vm_admin_user }}"
      custom_script: |
        {% if ovirt_vm_cloud_init_extras is defined %}
        {{ ovirt_vm_cloud_init_extras }}
        {% else %}
        # DEBUG
        {% endif %}
