---
- name: "Add master nodes"
  include_tasks: master_nodes.yml
  when: role == 'master'

- name: "Add worker nodes"
  include_tasks: worker_nodes.yml
  when: role == 'node'

- name: "Add special nodes"
  include_tasks: special_nodes.yml
  when: role == 'special'



