---

- name: "Ensure packages are installed"
  dnf:
    name:
      - nm-connection-editor
      - NetworkManager-libnm
      - python3-libsemanage
      - python3-policycoreutils
    state: present

- name: "Setup"
  include_tasks: setup.yml
  with_dict:  "{{ system_networks }}"
  loop_control:
      loop_var: "network"
