---
#### BRIDGE -> INTERFACE SETUP ####
- name: "Check if Bridge slave already exists for network {{ network.key }}"
  command: "nmcli -f GENERAL.STATE con show {{ network.key }}_slave"
  when: "network.value.interface is defined"
  register: conn_status_slave
  ignore_errors: yes

- name: Attach Slave to Bridge
  command: "nmcli con add type bridge-slave con-name {{ network.key }}_slave ifname {{ lookup( 'vars', network.value.interface) }} master {{ network.key }}"
  when:
    - "network.value.interface is defined"
    - "conn_status_slave.rc != 0"


