dns_server: 10.0.5.2

dhcp_range_start: 50
dhcp_range_end:   200

networks:
  wan:
    gateway:    "10.0.0.1/24"
    managed_by: "wan"
    subdomain:  "dhcp"
  server:
    gateway:    "10.0.2.1/24"
    managed_by: "solar"
    subdomain:  "srv"
    static_mappings:
      infinity:
        mac:  "90:E2:BA:3F:27:D0"
        ip:   "10.0.2.2"
      blackbird:
        mac:  "90:E2:BA:34:82:AA"
        ip:   "10.0.2.3"
      inferno:
        mac:  "90:E2:BA:3F:27:DA"
        ip:   "10.0.2.4"
      phoenix:
        mac:  "90:E2:BA:3F:25:D6"
        ip:   "10.0.2.5"
  virtual:
    gateway:    "10.0.4.1/24"
    managed_by: "solar"
    subdomain:  "vm"
    vlan_id:    "4"
  utility:
    gateway:    "10.0.5.1/24"
    managed_by: "solar"
    subdomain:  "nix"
    vlan_id:    "5"
    static_mappings:
      ipa:
        ip:     "10.0.5.2"
      nas:
        mac:    "56:6f:7b:93:00:00"
        ip:     "10.0.5.4"
  zoned:
    gateway:    "10.0.6.1/24"
    managed_by: "lunar"
    subdomain:  "zone"
    vlan_id:    "6"
  kube:
    gateway:    "10.0.7.1/24"
    managed_by: "solar"
    subdomain:  "kube"
    vlan_id:    "7"
  wireguard:
    gateway:    "10.0.8.1/24"
    managed_by: "flare"
    subdomain:  "wg"
    vlan_id:    "8"

