---
- name: "Ensure that anacron and wget is installed"
  dnf:
    name:
      - anacron
      - wget
    state: present

- name: "Make sure that the web group is created"
  group:
    name: web
    state: present

- name: "Make sure that acme user is created"
  user:
    name: acme
    groups: wheel,web
    createhome: yes
    state: present
    shell: /sbin/nologin
    home: /opt/acme

- name: "Ensure that certificate folder is created"
  file:
    path: "{{ certificate_location }}"
    group: web
    owner: root
    mode: '1770'
    state: directory

- name: "Download acme.sh"
  get_url:
    url: https://get.acme.sh
    dest: /tmp/acme.sh
    mode: '0777'

- name: "Install acme.sh"
  command: "/tmp/acme.sh"
  become: yes
  become_user: acme


