---

- name: "Set DHCP"
  vyos_command:
    commands:
      - configure
      - "set interfaces ethernet {{ item.key }} address {{ network_addresses[ item.value ] }}/24"
      - "set interfaces ethernet {{ item.key }} description {{ item.value }}"
      - commit
      - save
