- set_fact: vm_subdomain="{{ inventory_hostname.split('.')[1] }}"

- set_fact: network="{{ item.key }}"
  with_dict:
    - "{{ system_networks }}"
  when: "{{ vm_subdomain == item.value.subdomain }}"
