---
- set_fact: hypervisor_host="{{ groups['hypervisors'] | random }}" undef="True"
  when: hypervisor_host is undefined

- debug: msg="Hypervisor host was undefined, Deploying onto {{ hypervisor_host }}"
  when: undef is defined

- include: setup_image.yml
  delegate_to: "{{ hypervisor_host }}"
