---

- name: Install Virtualization packags
  dnf:
    name: '@virtualization'
    state: present

- name: Install cloud-utils
  dnf:
    name: cloud-utils
    state: present

- name: Install LXML
  dnf:
    name: python3-lxml
    state: present

- name: Set Sysctl Variable
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable and start Libvirt
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Remove Default network
  virt_net:
    command: destroy
    name: default

- virt_net:
    command: undefine
    name: default

- name: Remove all networks
  virt_net:
    command: info
  register: curr_vm_nets

- include: undefine_networks.yml
  with_dict:
    - "{{ curr_vm_nets.networks }}"

- name: "Define Libvirt Networks"
  include: define_networks.yml
  with_dict:
    - "{{ virt_networks }}"

- virt_net:
    command: info
  register: virt_networks

- virt_net:
    name: "{{ item.key }}"
    state: active
    command: start
  with_dict:
    - "{{ virt_networks.networks }}"

- virt_net:
    name: "{{ item.key }}"
    autostart: yes
  with_dict:
    - "{{ virt_networks.networks }}"
