---
- name: "Enable DNF Copr"
  command: "dnf copr enable -y jdoss/wireguard"

- name: "Update all packages"
  dnf:
    name: "*"
    state: latest

- name: "Reboot system"
  reboot:

- name: "Wait for host to come back online"
  wait_for_connection:

- name: "Install wireguard"
  dnf:
    name:
      - wireguard-dkms
      - wireguard-tools
    state: present

- name: "Modprobe wireguard"
  modprobe:
    name: wireguard
    state: present
