---

- name: "Create wireguard dir"
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: wheel
    mode: '0750'

- name: "Template out lightspeed wireguard conf"
  template:
    src: server.j2
    dest: "/etc/wireguard/wg0.conf"
    owner: root
    group: wheel
    mode: 0750

- name: "Enable and start wireguard"
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: yes
