---
- include_role:
    name: virt/ovirt/auth
  when: ovirt_auth is not defined

- name: "Get ovirt CA"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Delete ovirt CA"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'

