---
- name: "Add hosts to cluster"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/kube-cluster.yml"
  tasks:
    - name: "Add master and worker nodes"
      include_role:
        name: app/kubernetes/add_hosts
      vars:
        role: master
        hosts_to_add: "{{ master_nodes.count }}"

    - name: "Pause playbook to confirm that details are setup"
      pause:
        prompt: |
          ===============================================================================================
            CREATING NEW CLUSTER {{ cluster_name }}
          ===============================================================================================
            Please make sure that you had a dns records setup for the follwing
            {{ kubernetes_controlplane_dns_endpoint }} pointing to {{ kubernetes_controlplane_endpoint }}
            There will be {{ worker_nodes.count }} initial worker nodes and {{ master_nodes.count }} master nodes.
          ===============================================================================================
            The masters will be named as such:
              {{ cluster_name }}-{{ master_nodes.naming }}-RANDOMSTRING
            They will be created to the following specs
              CPUS:      {{ master_nodes.cores }}
              RAM:       {{ master_nodes.ram }}MB
              DISK SIZE: {{ master_nodes.disk }}GB
              NETWORK:   {{ master_nodes.network }}
          ===============================================================================================
            The workers will be named as such:
              {{ cluster_name }}-{{ worker_nodes.naming }}-RANDOMSTRING
            They will be created to the following specs
              CPUS:      {{ worker_nodes.cores }}
              RAM:       {{ worker_nodes.ram }}MB
              DISK SIZE: {{ worker_nodes.disk }}GB
              NETWORK:   {{ worker_nodes.network }}
          ===============================================================================================
            The special nodes will be named as such:
              {{ cluster_name }}-{{ special_nodes.naming }}-RANDOMSTRING
            They will be created to the following specs
              CPUS:      {{ special_nodes.cores }}
              RAM:       {{ special_nodes.ram }}MB
              DISK SIZE: {{ special_nodes.disk }}GB
              NETWORK:   {{ special_nodes.network }}
          ===============================================================================================
            Press enter to continue
          ===============================================================================================
        echo: no

- name: "Deploy kube-masters"
  hosts: kube-master
  gather_facts: no
  roles:
    - role: virt/ovirt/virtual_machine
      state: present
    - role: virt/ovirt/virtual_machine
      state: started

- name: "Setup Multi-master control planes"
  hosts: kube-master
  become: yes
  gather_facts: yes
  roles:
    - role: app/kubernetes/multi-master

- name: "Create cluster on kubernetes master"
  hosts: "{{ groups['kube-master'] | first }}"
  gather_facts: yes
  become: yes
  tasks:
    - name: "Create certificate key"
      command: "kubeadm alpha certs certificate-key"
      register: kubeadm_cert_key

    - name: "Initialize the cluster"
      command: |
        kubeadm init --pod-network-cidr=10.88.0.0/16
        --control-plane-endpoint {{ kubernetes_controlplane_dns_endpoint | mandatory }}:6445
        --upload-certs
        --certificate-key {{ kubeadm_cert_key.stdout }}
    - name: "Get Join token"
      command: "kubeadm token create --print-join-command"
      register: join_command

    - name: Copy file with owner and permissions
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/kubeconf.conf
        flat: yes

- name: "Join masters to cluster"
  hosts: "{{ groups['kube-master'] | difference(groups['kube-master'] | first) }}"
  become: yes
  vars:
    join_token_command: "{{ hostvars[groups['kube-master'][0]].join_command.stdout }}"
    certificate_key: "{{ hostvars[groups['kube-master'][0]].kubeadm_cert_key.stdout }}"
  tasks:
    - name: "Initialie the cluster"
      command: "{{ join_token_command }} --control-plane --certificate-key {{ certificate_key }}"

- name: "Import extra playbook"
  import_playbook: scale_cluster.yml
