---
- name: "Add hosts to cluster"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/kube-cluster.yml"
  roles:
    - virt/ovirt/auth
  tasks:
    - name: "Pull ovirt vms"
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name="{{ cluster_name }}-knode-*"
      register: result
