---
- block:
  - name: "Set DNS zone"
    ipa_dnszone:
      ipa_host: "{{ inventory_hostname }}"
      ipa_pass: "{{ freeipa_admin_password }}"
      state: present
      dynamicupdate: true
      zone_name: "{{ item.value.subdomain }}.{{ domain }}"
      validate_certs: no
    with_dict: "{{ networks }}"
  - name: "Set ARPA DNS zone"
    ipa_dnszone:
      ipa_host: "{{ inventory_hostname }}"
      ipa_pass: "{{ freeipa_admin_password }}"
      state: present
      dynamicupdate: true
      zone_name: "{{ (item.value.gateway | ipaddr('subnet') | ipaddr('revdns'))[2:] }}"
      validate_certs: no
    with_dict: "{{ networks }}"
  delegate_to: localhost
