---
- debug: msg="{{ record }} will be given an {{ type }} record with a value of {{ value }} and a ttl of 30"
- name: "Create IPV4 Address"
  cloudflare_dns:
    zone: "{{ domain }}"
    record: "{{ record }}"
    type: "{{ type }}"
    ttl: 120
    value: "{{ value }}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
    state: present
  delegate_to: localhost
