---
- name: "Setup a Mail server using docker"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Delete the Mail server and docker"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'
