---
- debug:
    msg: "{{ networks }}"
- name: "Creation of static DHCP mappings for VyOS"
#  template: src=setup.j2 dest=/tmp/test
#  delegate_to: localhost
  vyos_config:
    src: setup.j2
    save: yes

