---

- name: get device name
  set_fact:
    device_name: "{{ item.key }}"
    vm_disk_speed: "blaze"
  with_dict: "{{ ansible_devices }}"
  when: "item.key.startswith('nvme')"

- name: Create a Partition for LVM
  parted:
    device: "/dev/{{ device_name }}"
    number: 1
    state: present
    label: gpt
    flags: [ lvm ]
    name: blaze
  when: "{{ vm_disk_speed  == 'blaze' }}"

- name: Create Volume group on NVME Device
  lvg:
    vg: blaze
    pvs: "/dev/{{ device_name }}p1"
    pesize: 32
  when: "{{ vm_disk_speed  == 'blaze' }}"

- name: Get volume groups
  set_fact: vm_disk_speed="{{ item.key }}"
  with_dict: "{{ ansible_lvm.vgs }}"
  when: single_disk

- name: Create Logical volume
  lvol:
    vg: "{{ vm_disk_speed }}"
    lv: virt
    size: 150G

- name: Create filesystem on Logical volume
  filesystem:
    fstype: xfs
    dev: "/dev/{{ vm_disk_speed }}/virt"

- name: Create mount directories
  file:
    path: "/storage/loc/{{ vm_disk_speed }}/virt"
    state: directory
    mode: '0755'

- name: Mount device
  mount:
    path: "/storage/loc/{{ vm_disk_speed }}/virt"
    src: "/dev/{{ vm_disk_speed }}/virt"
    fstype: xfs
    state: mounted
