---

- name: "Install Certificate Authority for letsencrypt"
  shell: "wget https://letsencrypt.org/certs/isrgrootx1.pem | sudo ipa-cacert-manage install isrgrootx1.pem -p {{ ipa_password }} -n ISRGRootCAX1 -t C,,"

- name: "Install second Certificate Authority for letsencrypt"
  shell: "wget https://letsencrypt.org/certs/letsencryptauthorityx3.pem | sudo ipa-cacert-manage install letsencryptauthorityx3.pem -p {{ ipa_password }} -n ISRGRootCAX3 -t C,,"

- name: "Update Certificates"
  command: ipa-certupdate

- name: "Install SSL certificates from Letsencrypt"
  command: "ipa-server-certinstall -w -d {{ certificate_location }}/fullchain.pem {{ certificate_location }}/key.pem -p {{ ipa_password }} --pin='' -v"

- name: "Restart IPA"
  command: ipactl restart
