---

- name: "Deploy router (TESTING)"
  hosts: solar
  gather_facts: no
  connection: network_cli
  vars:
    ansible_host: 10.0.0.69
  roles:
#    - virt/deployment
#    - common/github_ssh_key
    - network/vyos


