---
- name: "Create Metadata dir for {{ hostname }}"
  file:
    path: "/tmp/{{ full_hostname }}"
    state: directory
    owner: qemu
    group: qemu
    mode: '0755'

- set_fact: tmp_fpath="/tmp/{{ full_hostname }}"

- name: "Create meta-data file for {{ hostname }}"
  template:
    src: meta-data.j2
    dest: "{{ tmp_fpath }}/meta-data"
    owner: qemu
    group: qemu
    mode: '0755'

- name: "Create user-data file for {{ hostname }}"
  template:
    src: user-data.j2
    dest: "{{ tmp_fpath }}/user-data"
    owner: qemu
    group: qemu
    mode: '0755'

- name: "Create ISO image for cloud-init"
  command: "cloud-localds {{ vm_dir }}/{{ hostname }}.iso {{ tmp_fpath }}/user-data {{ tmp_fpath }}/meta-data"


- set_fact: cloud_init_opts="--disk {{ vm_dir }}/{{ hostname }}.iso,device=cdrom"

