---
- setup:
- set_fact: lvm_name="{{ ansible_lvm.lvs.virt.vg }}"
- set_fact: base_image_dir="/storage/loc/{{ lvm_name }}/virt/base" vm_dir="/storage/loc/{{ lvm_name }}/virt/images"
- set_fact: full_hostname="{{ inventory_hostname }}" hostname="{{ inventory_hostname.split('.')[0] }}"
- name: "Ensure file owner of file {{ base_image_dir }}/{{ base_image_name }} is set to qemu"
  file:
    path: "{{ base_image_dir }}/{{ base_image_name }}"
    owner: qemu
    group: qemu
    mode: '0755'

- name: "Create VMI Based from Backing image"
  command: qemu-img create -f qcow2 -b {{ base_image_dir }}/{{ base_image_name }} {{ vm_dir }}/{{ full_hostname }} {{ disk_size }}

- include_tasks: cloud_init.yml
  when: cloud_init

- set_fact: vm_subdomain="{{ inventory_hostname.split('.')[1] }}"
- set_fact: network="{{ item.key }}"
  with_dict:
    - "{{ system_networks }}"
  when: vm_subdomain == item.value.subdomain

- set_fact: network="default"
  when: network == "virtual"

- set_fact:
    vm_net_opts:  "--network=network:{{ network }}"
  when: vm_net_opts is undefined

- set_fact:
    vm_req_opts:  "--name {{ full_hostname }} --vcpus {{ cpus }} --memory {{ memory }} --import"
    vm_disk_opts: "--disk '{{ vm_dir }}/{{ full_hostname }}',format=qcow2,bus=virtio"
    vm_misc_opts: "--os-type=linux --os-variant=archlinux --graphics none --noautoconsole"

- name: "Install virtual machine"
  command: virt-install {{ vm_req_opts }} {{ vm_disk_opts }} {{ vm_misc_opts }} {{ vm_net_opts }} {{ cloud_init_opts }}

- name: "Pause for 2 seconds"
  pause:
    seconds: 2

- name: "Eject the iso"
  command: virsh change-media {{ full_hostname }} sda --eject --config
  when: cloud_init

- name: "Remove {{ tmp_fpath }}"
  file:
    path: "{{ tmp_fpath }}"
    state: absent
  when: cloud_init

- name: "Remove ISO in {{ vm_dir }}/{{ hostname }}.iso"
  file:
    path: "{{ vm_dir }}/{{ hostname }}.iso"
    state: absent
  when: cloud_init

- set_fact: ansible_host="{{ network_address | ipaddr('address') }}"
  when: network_address | ipaddr != False

