---

- name: "Add necessary pre-requisites to installing docker"
  dnf:
    name:
      - dnf-plugins-core
      - grubby
    state: present

- name: "Run DNF config manager to add the docker repo"
  command:
    cmd: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
    warn: false

- name: "Install docker"
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
    state: present

- name: "Run grubby to update the commandline arguements"
  command:  grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

- name: "Enable the Docker service"
  systemd:
    name: docker
    enabled: yes
