- name: "Define Libvirt Network"
  virt_net:
    autostart: yes
    command: define
    name: "{{ item.key }}"
    xml: "<network><name>default</name><forward mode='bridge'/><bridge name='{{ item.key }}'/></network>"
  when: item.key == "virtual"

- name: "Define Libvirt Network"
  virt_net:
    autostart: yes
    command: define
    name: "{{ item.key }}"
    xml: "<network><name>{{ item.key }}</name><forward mode='bridge'/><bridge name='{{ item.key }}'/></network>"
  when: item.key != "virtual"
