---
- include_role:
    name: virt/ovirt/auth
  when: ovirt_auth is not defined

- name: "Import ovirt template for use"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Delete imported ovirt template"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'

