---
- name: "Create ovirt networks"
  include_tasks: setup.yml
  when: state|default('present') == 'present'

- name: "Delete ovirt networks"
  include_tasks: destroy.yml
  when: state|default('present') == 'absent'

