---
- name: "Modify template for Kubernetes cluster"
  hosts: kube-master
  gather_facts: no
  vars:
    ovirt_base_template_name: "base_image"
    ovirt_base_template_savename: "kubernetes"
    ovirt_template_extra_repos:
      kubernetes:
        url: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
        gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
        name: "Kubernetes"
    ovirt_template_extra_commands:
      - "modprobe br_netfilter"
      - "echo 'br_netfilter' >> /etc/modules-load.d/br_netfilter.conf"
      - "echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/k8s.conf"
      - "echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/k8s.conf"
      - "echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/k8s.conf"
      - "echo 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint=\"unix:///var/run/crio/crio.sock\"' >> /etc/sysconfig/kubelet"
      - "grubby --update-kernel=ALL --args='systemd.unified_cgroup_hierarchy=0'"
      - "yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"
      - "dnf module enable -y cri-o:1.17"
      - "dnf install -y cri-o kubernetes-cni nfs-utils logrotate"
    ovirt_template_enabled_services:
      - "kubelet"
      - "crio"
      - "logrotate.timer"
  roles:
    - role: virt/ovirt/modify_template
