---
- name: "Setup VM"
  hosts: apollo
  gather_facts: no
  roles:
#    - role: vm_deployment

- name: "Wait for a few seconds"
  hosts: localhost
  tasks:
  - name: "Sleep the thread"
    pause:
      seconds: 60

- name: "Setup Kubernetes on master node"
  hosts: apollo-master
  roles:
#    - { role: setup_cluster, action: create }
#    - { role: setup_cluster, action: kubeconf }
#    - { role: setup_cluster, action: token }

- name: "Add Kubernetes Nodes to the network"
  hosts: apollo-nodes
  vars:
    join_token_command: "{{ hostvars[groups['apollo-master'][0]].join_command.stdout }}"
  roles:
#    - { role: setup_cluster, action: join }

- name: "Install Ceph RBD onto nodes"
  hosts: apollo
  tasks:
    - name: "Install Ceph RBD"
      dnf:
        name:
          - nfs-utils
          - ceph-common
          - ceph
          - ceph-fuse
        state: present
