---
- name: "Setup VM"
  hosts: flare
  gather_facts: no
  roles:
    - role: vm_deployment

- name: "Wait for a few seconds"
  hosts: localhost
  tasks:
   - name: "Sleep the thread"
     pause:
       seconds: 60

- name: "Setup Kubernetes on master node"
  hosts: flare-master
  roles:
    - { role: setup_cluster, action: create }
    - { role: setup_cluster, action: kubeconf }
    - { role: setup_cluster, action: token }

- name: "Add Kubernetes Nodes to the network"
  hosts: flare-nodes
  vars:
    join_token_command: "{{ hostvars[groups['flare-master'][0]].join_command.stdout }}"
  roles:
    - { role: setup_cluster, action: join }
