---
- name: "Create static DHCP Reservations"
  hosts: solar
  gather_facts: no
  tasks:
  roles:
#    - role: net/vyos/phys_network
#    - role: net/vyos/dhcp
    - role: net/vyos/static_dhcp
      state: "present"
