---
- name: "Deploy Solar infrastructure"
  hosts: solar
  gather_facts: no
  tasks:
  roles:
    - role: net/vyos/init
      state: present
#    - role: net/vyos/phys_network
#      state: present
    - role: net/vyos/dhcp
      state: present
    - role: net/vyos/dns
      state: present
#    - role: net/vyos/static_dhcp
#      state: present
