---
- name: "Deploy Solar infrastructure"
  hosts: solar
  gather_facts: no
  tasks:
  roles:
    - role: net/vyos/init
    - role: net/vyos/phys_network
    - role: net/vyos/dhcp
    - role: net/vyos/dns
    - role: net/vyos/static_dhcp
