---
- name: "Create Kubernetes cluster Virtual Machines and start them"
  hosts: kube-cluster
  gather_facts: no
  roles:
    - role: virt/ovirt/virtual_machine
      state: present
    - role: virt/ovirt/virtual_machine
      state: started
- name: "Initialize the kubernetes cluster"
  hosts: kube-master
  gather_facts: yes
  become: yes
  tasks:
    - name: "Initialize the cluster"
      command: "kubeadm init --pod-network-cidr=10.88.0.0/16"

    - name: "Get Join token"
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy file with owner and permissions
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/kubeconf.conf
        flat: yes

- name: "Join nodes to kubernetes cluster"
  hosts: kube-nodes
  gather_facts: yes
  become: yes
  vars:
    join_token_command: "{{ hostvars[groups['kube-master'][0]].join_command.stdout }}"
  tasks:
    - name: "Initialie the cluster"
      command: "{{ join_token_command }}"

