---
- name: "Deploy ovirt networks"
  hosts: localhost
  gather_facts: no
  tasks:
  roles:
    - role: virt/ovirt/auth
      state: present
    - role: virt/ovirt/import_template
      state: absent

