---
- name: "Deploy ovirt networks"
  hosts: testvm.vm.oxide.one
  gather_facts: no
  roles:
    - role: virt/ovirt/auth
      delegate_to: 127.0.0.1
    - role: virt/ovirt/virtual_machine
      state: present
      delegate_to: 127.0.0.1
    - role: virt/ovirt/virtual_machine
      state: started
      delegate_to: 127.0.0.1
