---
- name: "Deploy Virtual Machine"
  hosts: torrent.wg.oxide.one
  gather_facts: no
  roles:
    #- role: virt/ovirt/virtual_machine
      #state: present
    #- role: virt/ovirt/mac_info
    #- role: net/vyos/static_dhcp
      #delegate_to: "lunar.nix.oxide.one"
    #- role: virt/ovirt/virtual_machine
      #state: started

- name: "Install docker and setup packages"
  hosts: torrent.wg.oxide.one
  roles:
#    - role: common/docker
#      state: present
    - role: common/nfs_mounts
      state: present
