---
- name: "Debug stuff"
  hosts: lightspeed.oxide.one
  gather_facts: no
  vars:
    wireguard_publickey: hostvars['solar.oxide.one'].wireguard_publickey
  roles:
#    - cloud/cloudflare
#    - cloud/digitalocean
     - app/haproxy_entrypoint
