---
- name: "Deploy ovirt networks"
  hosts: localhost
  gather_facts: no
  tasks:
  roles:
    - role: virt/ovirt/get_ca
      state: present
    - role: virt/ovirt/auth
      state: present
    - role: virt/ovirt/networks
      state: present

