---
- name: "Deploy Dynamic DNS and Letsencrypt certs for FreeIPA"
  hosts: lunar
  gather_facts: no
  roles:
    - role: virt/ovirt/virtual_machine
      state: present
    - role: virt/ovirt/mac_info
    - role: net/vyos/static_dhcp
      delegate_to: "solar.dhcp.oxide.one"
    - role: virt/ovirt/virtual_machine
      state: started
