---
- import_role: name=common/docker
  state: present
  become: yes

- import_role: name=common/nfs_mounts
  state: present
  become: yes

- import_role: name=common/acme
  state: present
  become: yes

- name: "Template out Docker-compose file"
  template:
    src: docker-compose.j2
    dest: /tmp/docker-compose.yml

- name: "Launch services"
  docker_compose:
    project_src: /tmp
    state: present
  become: yes

