---
- name: "Get certificates for domain"
  command: "{{ certificate_location }}/.acme.sh/acme.sh --force --issue --dns dns_cf -d {{ ssl_certs | join(' -d ') }} --key-file {{ certificate_location }}/key.pem --cert-file {{ certificate_location }}/cert.pem --fullchain-file {{ certificate_location }}/fullchain.pem "
  environment:
    CF_Key: "{{ cloudflare_api_key }}"
    CF_Email: "{{ cloudflare_email }}"
  args:
    executable: /bin/bash
  become: yes
  become_user: acme
  register: acme_output
- debug: msg="{{ acme_output.stdout }}"
- name: "Set permissions on certs"
  file:
    path: "{{ certificate_location }}"
    group: web
    mode: '0770'
    recurse: yes


