---
- name: "Deploy Dynamic DNS and Letsencrypt certs for FreeIPA"
  hosts: nameservers
  gather_facts: no
  roles:
#    - role: common/acme
    - role: app/freeipa/letsencrypt
#    - role: app/freeipa/dns_zones
